language: generic
sudo: required
services:
  - docker:

before_install:
  - docker build -t majidkhan59/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true majidkhan59/docker-react npm run test

#deploy:
#  provider: elasticbeanstalk
#  region: "us-east-2"
#  app: "docker-react"
#  env: "Docker-env"
#  bucket_name: "elastickbeanstalk-us-east-1-2312"
#  on:
#   branch: master
#  access_key_id: $AWS_ACCESS_KEY
#  secret_access_key:
#    secure: "$AWS_SECRET_KEY"
